apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      name: backend-rc
      labels:
        app: backend
    spec:
      containers:
      - name: mongo
        image: mongo:3.3
        ports:
        - containerPort: 27017