apiVersion: apps/v1
kind: Deployment
metadata:
  name: fend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fend

  template:

    metadata:
      name: fend-rc
      labels:
        app: fend
    spec:
      containers:
      - name: rsvp
        image: teamcloudyuga/rsvpapp
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_HOST
          value: mongo-svc