apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demp-voting-app

spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_vote:v1
        